{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cronjob.releaseName" . }}-secret
  labels:
    {{- include "cronjob.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "4"    
type: Opaque
data:
{{- with .Values.secret.secrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
