{{- range $jobname, $job := .Values.jobs }}
{{ if $job.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if (hasKey $job "serviceAccount") }}
  name: {{ $job.serviceAccount.name }}
  {{- else }}
  name: {{ $.Release.Name}}-{{ $jobname }}
  {{- end }}
  labels:
    {{- include "cronjob.labels" $ | nindent 4 }}
    cron: {{ $jobname }}
  {{- if and (hasKey $job "serviceAccount") (hasKey $job "serviceAccount.annotations") }}
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
