apiVersion: v2
name: cloudflare-ddns
description: Cloudflare DDNS updater
type: application
version: 0.1.4
appVersion: "1"
sources:
  - https://github.com/favonia/cloudflare-ddns
keywords:
    - helm
    - chart  
    - k8s
    - cloudflare
    - cloudflare-ddns
home: https://github.com/clouddrove/helmchart
maintainers:
    - name: CloudDrove Inc
      email: hello@clouddrove.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/clouddrove/helmchart
    - name: support
      url: https://github.com/clouddrove/helmchart/issues
  artifacthub.io/maintainers: |
    - name: CloudDrove
      email: hello@clouddrove.com
  artifacthub.io/images: |
    - name: cloudflare-ddns
      image: favonia/cloudflare-ddns:latest
  artifacthub.io/changes: |
    - kind: added
      description: Artifact Hub metadata annotations
