{{- if not .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-ddns.fullname" . }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.key }}: {{ required "Set .Values.secret.value (or provide secret.name to use an existing Secret)" .Values.secret.value | quote }}
{{- end }}
