# Artifact Hub repository metadata file

# Repository unique ID (you already have this one from Artifact Hub)
repositoryID: 09c0151e-5789-4eb1-83b1-0133b27cc159

# Basic info about your repository
name: clouddrove
displayName: CloudDrove
description: A collection of Helm charts maintained by CloudDrove
homeURL: https://charts.clouddrove.com/
repoURL: https://github.com/clouddrove/helmchart
type: helm

# Required for ownership verification and verified publisher badge
owners:
  - name: CloudDrove
    email: hello@clouddrove.com
  - name: Anmol Nagpal
    email: anmol@clouddrove.com

# Optional: Add publisher info
publisher:
  name: CloudDrove
  email: hello@clouddrove.com
  url: https://github.com/clouddrove/helmchart
