repositoryID: 09c0151e-5789-4eb1-83b1-0133b27cc159
name: clouddrove
displayName: CloudDrove
description: A collection of Helm charts maintained by Clouddrove
homeURL: https://charts.clouddrove.com/
repoURL: https://charts.clouddrove.com/
type: helm
publisher:
  name: clouddrove
  email: hello@clouddrove.com
  url: https://charts.clouddrove.com/
owners:
  - name: clouddrove
    email: hello@clouddrove.com
