{{- with .Values.members }}
{{- include "rbac.validateNamespaces" . }}
{{- range $i, $u := . }}
{{- $isSA := eq ($u.subjectKind | default "ServiceAccount") "ServiceAccount" }}
{{- if hasKey $u "createNamespace" | ternary $u.createNamespace $isSA }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $u.namespace | default (printf "ns-%s" $u.name) | quote }}
  labels:
    {{- include "rbac.labels" $ | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
