{{- if .Values.cronJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name:  {{ include "vigil.fullname" . }}-migration
  labels:
    {{- include "vigil.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  startingDeadlineSeconds: {{ .Values.cronJob.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "vigil.fullname" . }}
          labels:
            {{- include "vigil.labels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          containers:
          - name: {{ include "vigil.fullname" . }}
            image: "{{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}"
            imagePullPolicy: {{ .Values.cronJob.image.pullPolicy }}
            resources:
              {{- toYaml .Values.cronJob.resources | nindent 16 }}
            envFrom:
            {{- if and (not .Values.cronJob.configmap.enabled) }}
              []
            {{- end }}
            {{- if .Values.cronJob.configmap.enabled }}
              - configMapRef:
                  name: {{ include "vigil.fullname" . }}
            {{- end }}
            {{- if .Values.cronJob.secret.enabled }}
              - secretRef:
                  name: {{ include "vigil.fullname" . }}
            {{- end }}  
{{- end }}

