{{- if .Values.poddisruptionbudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ include "helmchart.namespace" . }}
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.poddisruptionbudget.minAvailable | quote }}
  selector:
    matchLabels:
      {{- include "helmchart.selectorLabels" . | nindent 6 }}
{{- end}}    