{{- if .Values.storageClass.persistence.enabled -}}
{{- if not .Values.storageClass.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "vigil.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vigil.name" . }}
    helm.sh/chart: {{ include "vigil.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.storageClass.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storageClass.persistence.size | quote }}
{{- if not .Values.storageClass.create }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ default (include "vigil.fullname" .) .Values.storageClass.storageClassName }}"
{{- end }}
{{- end -}}
{{- end -}}