{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vigil.fullname" . }}-secret
  namespace: {{ include "vigil.namespace" . }}
  labels:
    {{- include "vigil.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "4"   
type: Opaque
data:
  vigil.cfg: {{ .Values.secretConfig | b64enc }}
{{- end}}