{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vigil.fullname" . }}
  namespace: {{ include "vigil.namespace" . }}
  labels:
    {{- include "vigil.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "vigil.selectorLabels" . | nindent 4 }}
    {{- include "vigil.podLabels" . | nindent 4 }}
{{- end }}    
