{{- if .Values.metrics.enabled }}
# This object requires CustomResourceDefinition (crds).
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vigil.fullname" . }}-service-monitor
  labels:
    {{- include "vigil.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  selector:
    matchLabels:
      {{- include "vigil.labels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.metrics.portName }}
  {{- end }}
