{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "helmchart.namespace" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.namespace.annotations | nindent 4 }}
{{- end }}
