apiVersion: v1
entries:
  cronjob:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-07T10:04:32.782121986Z"
    description: A chart for cron jobs
    digest: 7ea65aaf37e3c03fa2c5e1b7f08cc3806a96d988de971b6eb22bd38a49229a62
    home: https://github.com/clouddrove/helmchart
    keywords:
    - cronjob
    - helm
    - k8s
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc.
    name: cronjob
    urls:
    - https://charts.clouddrove.com/charts/cronjob-0.0.1.tgz
    version: 0.0.1
  helmchart:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-06-06T19:40:01.872552833Z"
    description: A Helm chart for Kubernetes
    digest: 54522d217526ecd22d7a7bbedea96650f41cacce684f741a823b8f55c2e1220e
    home: https://github.com/clouddrove/helmchart
    icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
    keywords:
    - helm
    - chart
    - k8s
    - helm-chart
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc
    name: helmchart
    type: application
    urls:
    - https://charts.clouddrove.com/charts/helmchart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.8
    created: "2023-06-06T19:27:37.809240414Z"
    description: A Helm chart for Kubernetes
    digest: 992f0668bf79708ed920b2f310b3990c28882a92a8ac1b937ea23dfdf00ab0a7
    home: https://github.com/clouddrove/helmchart
    icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
    keywords:
    - helm
    - chart
    - k8s
    - helm-chart
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc
    name: helmchart
    type: application
    urls:
    - https://charts.clouddrove.com/charts/helmchart-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-07T10:04:32.783272491Z"
    description: A Helm chart for Kubernetes
    digest: 77f3c81db4b20ad8042908df918c2a08a9063f40c4b304c4297bf43ed7219f2d
    home: https://github.com/clouddrove/helmchart
    icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
    keywords:
    - helm
    - chart
    - k8s
    - helm-chart
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc
    name: helmchart
    type: application
    urls:
    - https://charts.clouddrove.com/charts/helmchart-0.0.1.tgz
    version: 0.0.1
generated: "2023-06-07T10:04:32.780753179Z"
