apiVersion: v1
entries:
  cronjob:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-07T10:21:33.917494836Z"
    description: A chart for cron jobs
    digest: d8423f61e957c9250037c0e6d3213d13c13d23cb7377a541c27f6638d1b231bf
    home: https://github.com/clouddrove/helmchart
    keywords:
    - cronjob
    - helm
    - k8s
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc.
    name: cronjob
    urls:
    - https://charts.clouddrove.com/charts/cronjob-0.0.1.tgz
    version: 0.0.1
  helmchart:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2023-06-06T19:40:01.872552833Z"
    description: A Helm chart for Kubernetes
    digest: 54522d217526ecd22d7a7bbedea96650f41cacce684f741a823b8f55c2e1220e
    home: https://github.com/clouddrove/helmchart
    icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
    keywords:
    - helm
    - chart
    - k8s
    - helm-chart
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc
    name: helmchart
    type: application
    urls:
    - https://charts.clouddrove.com/charts/helmchart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.8
    created: "2023-06-06T19:27:37.809240414Z"
    description: A Helm chart for Kubernetes
    digest: 992f0668bf79708ed920b2f310b3990c28882a92a8ac1b937ea23dfdf00ab0a7
    home: https://github.com/clouddrove/helmchart
    icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
    keywords:
    - helm
    - chart
    - k8s
    - helm-chart
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc
    name: helmchart
    type: application
    urls:
    - https://charts.clouddrove.com/charts/helmchart-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-06-07T10:21:33.918645248Z"
    description: A Helm chart for Kubernetes
    digest: 1294c38ed5c9231fd9c3bdb35faec0cc25065f97320b4f1e03a73996fa921949
    home: https://github.com/clouddrove/helmchart
    icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
    keywords:
    - helm
    - chart
    - k8s
    - helm-chart
    maintainers:
    - email: hello@clouddrove.com
      name: CloudDrove Inc
    name: helmchart
    type: application
    urls:
    - https://charts.clouddrove.com/charts/helmchart-0.0.1.tgz
    version: 0.0.1
generated: "2023-06-07T10:21:33.916574126Z"
