apiVersion: v1
entries:
  vigil-1.0.1:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-10-11T02:22:39.983159+05:30"
    description: A Helm chart for a vigil-1.0.1
    digest: 2eb77e1f302b812da3d181b43fcd80bea85e628a4d76e3b1c9f8712b3d96e956
    icon: https://raw.githubusercontent.com/akonverma97/testecr/main/github-logo.png
    name: sample-node-app
    type: application
    urls:
    - https://github.com/clouddrove/helmchart/blob/gh-pages/charts/vigil-1.0.1.tgz
    version: 1.0.1
generated: "2025-10-11T02:22:39.982389+05:30"