{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "changeme.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "4"    
data:
{{- with .Values.configmap.configs }}
  {{- toYaml . | nindent 2 -}}
  {{- end}}
{{- end}}