{{- if .Values.poddisruptionbudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "changeme.fullname" . }}
  labels:
    {{- include "changeme.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdbMinAvailable }}
  selector:
    matchLabels:
      {{- include "changeme.selectorLabels" . | nindent 6 }}
{{- end}}    