{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: changeme-secret
  labels:
    {{- include "changeme.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "4"    
type: Opaque
data:
{{- with .Values.secrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc}}
  {{- end }}
{{- end }}
{{- end }}