apiVersion: v2
appVersion: 1.0.1
description: Self-hosted microservices status page that monitors your infrastructure and sends alerts via Slack, Email, and SMS.
home: https://github.com/clouddrove/vigil
icon: https://emojis.slackmojis.com/emojis/images/1643514183/1491/kubernetes.png?1643514183
keywords:
- helm
- chart
- k8s
- helm-chart
maintainers:
- email: hello@clouddrove.com
  name: Clouddrove Inc
name: vigil
type: application
version: 1.0.3
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/clouddrove/helmchart
    - name: support
      url: https://github.com/clouddrove/helmchart/issues
  artifacthub.io/maintainers: |
    - name: CloudDrove
      email: hello@clouddrove.com
  artifacthub.io/images: |
    - name: vigil
      image: valeriansaliou/vigil:latest
  artifacthub.io/changes: |
    - kind: added
      description: Artifact Hub metadata annotations
