{{- if .Values.istio.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }} 
  gateways:
    {{- if .Values.istio.gateway.enabled }}
    - {{ default .Release.Namespace .Values.istio.gateway.namespace }}/{{ include "helmchart.fullname" . }}-istio-gateway
    {{- else }}  
    {{- range .Values.istio.gateway.names }}
    - {{ . }}
    {{- end }}
    {{- end }}     
  http:
  - route:
    - destination:
        host: {{ include "helmchart.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}