{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }} 
  gateways:
    {{- range .Values.istio.gateway.names }}
    - {{ . }}
    {{- end }} 
  http:
  - route:
    - destination:
        host: {{ include "helmchart.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}