name: changelog
permissions: write-all

on:
  workflow_run:
    workflows: ["Release Charts"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  call-workflow-changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/changelog.yml@master
    with:
      branch: 'master'
