name: Helm CI
on: [push, pull_request]
jobs:
  helm-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: helm-check-helmchart
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./charts/helmchart
        CHART_VALUES: ./tests/helmchart/override-test.yaml
