name: Helm CI
on: [push, pull_request]
jobs:
  helm-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: helm-check-changeme
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./charts/changeme
        CHART_VALUES: ./charts/changeme/values/test.yaml